(()=>{
const APP_VERSION="2.0.0"; const UPDATED="12 Juli 2026";
const services=[["Guide", "https://ytconvguide.vercel.app/", "Panduan langkah demi langkah"], ["Docs", "https://ytconvdocs.vercel.app/", "Dokumentasi fitur dan teknis"], ["Status", "https://ytconvstatus.vercel.app/", "Kondisi seluruh layanan"], ["Tools", "https://ytconvtools.vercel.app/", "Peralatan link dan command"], ["Help", "https://ytconvhelp.vercel.app/", "Solusi error dan bantuan"], ["Pulse", "#", "Update dan kompatibilitas platform"]];
const searchData=[["Buka converter", "Unduh MP3 atau MP4", "https://ytconv.onrender.com/", "converter download mp3 mp4"], ["Panduan Windows", "Pasang yt-dlp, FFmpeg, dan Deno", "https://ytconvguide.vercel.app/", "windows cmd install"], ["Panduan Android", "Termux dan folder Download internal", "https://ytconvguide.vercel.app/", "android termux hp"], ["Dokumentasi cookies", "Cara ekspor dan menjaga cookies", "https://ytconvdocs.vercel.app/cookies", "cookies login extension"], ["Solusi error 403", "Penyebab dan langkah perbaikan", "https://ytconvhelp.vercel.app/", "403 forbidden error"], ["Solusi limit 429", "Terlalu banyak permintaan", "https://ytconvhelp.vercel.app/", "429 rate limit"], ["Cek status layanan", "Kondisi Converter, Guide, Docs, Tools, dan Help", "https://ytconvstatus.vercel.app/", "status down offline"], ["Bersihkan link", "Hapus parameter pelacak dari URL", "https://ytconvtools.vercel.app/", "clean url link"], ["Buat command yt-dlp", "Command otomatis sesuai perangkat", "https://ytconvtools.vercel.app/", "command generator ytdlp"]];
const current=location.hostname;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function mount(){
 document.body.insertAdjacentHTML('afterbegin','<a class="yc-skip" href="#main-content">Lewati ke isi utama</a>');
 const main=document.querySelector('main'); if(main&&!main.id)main.id='main-content'; else if(!document.getElementById('main-content')){const t=document.querySelector('h1')||document.body.firstElementChild;if(t)t.id='main-content'}
 const links=services.map(([n,u,d])=>u==='#'?`<span class="yc-item"><strong>${n}</strong><small>${d} · proyek ini</small></span>`:`<a class="yc-item" href="${u}"><strong>${n}</strong><small>${d}</small></a>`).join('');
 document.body.insertAdjacentHTML('beforeend',`<div class="yc-ecosystem"><button class="yc-launch" aria-expanded="false" aria-controls="yc-panel">☰ Ekosistem</button></div><aside id="yc-panel" class="yc-panel" hidden aria-label="Navigasi YTConv"><div class="yc-panel-head"><h2>Cari di YTConv</h2><button class="yc-close" aria-label="Tutup">×</button></div><input class="yc-search" type="search" placeholder="Coba: 403, Android, cookies…" autocomplete="off"><div class="yc-results" hidden></div><div class="yc-links">${links}</div><div class="yc-tools"><a href="https://ytconv.onrender.com/">Buka Converter</a><a href="/privacy.html">Privasi</a><a href="/terms.html">Ketentuan</a><a href="/security.html">Keamanan</a></div><section class="yc-feedback"><p>Halaman ini membantu?</p><div class="yc-feedback-actions"><button data-vote="yes">Ya</button><button data-vote="no">Belum</button></div><div class="yc-feedback-note" aria-live="polite"></div></section></aside><div class="yc-version">v${APP_VERSION} · diperbarui ${UPDATED}</div>`);
 const panel=document.getElementById('yc-panel'),open=document.querySelector('.yc-launch'),close=document.querySelector('.yc-close'),input=document.querySelector('.yc-search'),results=document.querySelector('.yc-results'),linksBox=document.querySelector('.yc-links');
 function setOpen(v){panel.hidden=!v;open.setAttribute('aria-expanded',String(v));if(v)setTimeout(()=>input.focus(),30)} open.onclick=()=>setOpen(panel.hidden);close.onclick=()=>setOpen(false);document.addEventListener('keydown',e=>{if(e.key==='Escape')setOpen(false)});
 input.oninput=()=>{const q=input.value.toLowerCase().trim();if(!q){results.hidden=true;linksBox.hidden=false;return}const found=searchData.filter(x=>(x.join(' ')).toLowerCase().includes(q)).slice(0,8);results.innerHTML=found.length?found.map(([t,d,u])=>`<a class="yc-item" href="${u}"><strong>${esc(t)}</strong><small>${esc(d)}</small></a>`).join(''):'<div class="yc-item"><strong>Belum ketemu</strong><small>Coba kata lebih pendek atau buka Help Center.</small></div>';results.hidden=false;linksBox.hidden=true};
 panel.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{const vote=b.dataset.vote;const key='ytconv_feedback';const rows=JSON.parse(localStorage.getItem(key)||'[]');rows.push({vote,page:location.href,time:new Date().toISOString()});localStorage.setItem(key,JSON.stringify(rows.slice(-50)));panel.querySelector('.yc-feedback-note').textContent=vote==='yes'?'Makasih, jawabanmu tersimpan di perangkat ini.':'Makasih. Buka Help Center kalau masih mentok.';if(vote==='no')setTimeout(()=>location.href='https://ytconvhelp.vercel.app/',900)});
 try{const s=document.createElement('script');s.defer=true;s.src='/_vercel/insights/script.js';document.head.appendChild(s)}catch{}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
})();